{
 "title": "New dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Verbrauchter RAM in %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expression": "(1 - $A/$B)*100", "type": "math" }
   ]
  },
  {
   "title": "CPU Nutzung aktuell in %",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (mode) (\r\n  rate(node_cpu_seconds_total{mode=~\"idle|user|system\"}[5m])\r\n) *100",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Disk I/O Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_weighted_seconds_total{instance=\"node-exporter:9100\", job=\"node\", device=\"sda\"}[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Origins used for Recognition",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "pagination_mode": "none",
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://48.210.24.23:8001/origins",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  }
 ]
}